"""recreation db with torrent description table

Revision ID: 7a357aff93df
Revises: 
Create Date: 2020-04-27 14:41:04.293023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a357aff93df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('torrent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torrent_name', sa.String(), nullable=False),
    sa.Column('torrent_date', sa.DateTime(), nullable=False),
    sa.Column('torrent_size', sa.String(), nullable=False),
    sa.Column('torrent_file_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('torrent_file_link')
    )
    op.create_table('torrent_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('torrent_description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('role', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role'), 'user', ['role'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_role'), table_name='user')
    op.drop_table('user')
    op.drop_table('torrent_description')
    op.drop_table('torrent')
    # ### end Alembic commands ###
